### ISSUE TITLE
SecurityStatusReport breaks  6.x compatibility

### ISSUE THREAD

**Issue by andyhirsch** [georgringer/t3monitoring_client#11]
As there is no SecurityStatusReport in 6.x client import throws
PHP Fatal error:  Class 'TYPO3\\CMS\\Install\\Report\\SecurityStatusReport' not found in /[...]/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4469

**Comment by georgringer** [comment]
Wanna do a pull request?

**Comment by georgringer** [comment]
merged
