### ISSUE TITLE
Client fetch fails, class SecurityStatusReport does not exist in 6.2

### ISSUE THREAD

**Issue by liayn** [georgringer/t3monitoring_client#18]
`Got error 'PHP message: PHP Fatal error:  Class 'TYPO3\\CMS\\Install\\Report\\SecurityStatusReport' not found`

**Comment by wouter90** [comment]
Has already been fixed with https://github.com/georgringer/t3monitoring_client/commit/0490d39ec51c09f3b911034e02efaacce05bf1d3

**Comment by liayn** [comment]
Args... I tought my client was already on my own commit, which was after 0490d36, but it wasn't.

**Comment by liayn** [comment]
@georgringer Please make a new release.
