### ISSUE TITLE
Dispay Title

### ISSUE THREAD

**Issue by CarstenHager** [georgringer/t3monitoring_client#19]
Would be nice to see the title of the client .
![screenshot 2016-05-19 20 32 41](https://cloud.githubusercontent.com/assets/5907780/15405194/2d511cd6-1e01-11e6-97ed-ec6667400402.png)

**Comment by gerchomat** [comment]
You can set a title for the client!
You have to deactivate the "presentation mode" in the extension configuration in ext-manager.

**Comment by CarstenHager** [comment]
Oh sorry,
thank you!!!
