### ISSUE TITLE
compat_version() deprecated in TYPO3 v8

### ISSUE THREAD

**Issue by josefglatz** [georgringer/t3monitoring_client#22]
TYPO3 version check needs to be refactored in extension.

**Comment by jousch** [comment]
I actually don't get the point, why `\TYPO3\CMS\Core\Utility\GeneralUtility::compat_version` was deprecated, if it is necessary to check for the compat version of the core in future. @georgringer Is it enough to only check against the constant `TYPO3_branch` in future with something like

```php
if (version_compare(TYPO3_branch, '7.6', '>=')) {}
```
?

**Comment by georgringer** [comment]
solved
