### ISSUE TITLE
Client fetch fails: "Class 'TYPO3\CMS\Core\Database\ConnectionPool' not found"

### ISSUE THREAD

**Issue by andyhirsch** [georgringer/t3monitoring_client#33]
Since https://github.com/georgringer/t3monitoring_client/commit/46c4d7a4a34f63af1e599f0a315f39d9c762eb2f client fetch fails for TYPO3 versions < 8

ext_localconf.php Line 7:
Because TYPO3\CMS\Core\Utility\VersionNumberUtility exists since TYPO3 6 $version is always 9 for Versions >=6

**Comment by beathorst** [comment]
this will fix it: https://github.com/georgringer/t3monitoring_client/pull/34
