### ISSUE TITLE
Git Tags

### ISSUE THREAD

**Issue by beathorst** [georgringer/t3monitoring_client#35]
can you make tags after ich Pull-Request or logical steps?
Because it is not nice to use it with "dev-master" in composer. after composer update my monitoring was broken because of a bug in master

**Comment by georgringer** [comment]
i will release major version soon. if you are working on dev-master I would propose to add the sha1 of the commit you want to stay on.

**Comment by beathorst** [comment]
but it looks so ugly ;-)
"t3monitor/t3monitoring_client": "dev-master#bb58ca9d6649e7ea6eb55a4f46d731d7e0b9d215",

thanx for your work, I can wait for major
