### ISSUE TITLE
can't fetch data from client after install monitoring_client extension

### ISSUE THREAD

**Issue by kanow** [georgringer/t3monitoring_client#39]
On installing the extensions in ext-manager the em-configuration is prefilled with the secret hash. The setting for allowedIps and enableDebugForErrors are not written in LocalConfiguration. Therefore I can't fetching informations from the client. After a first saving of this configuration in ext-manager the settings are written in LocalConfiguration.php. Then I can fetching data from the client.
I'm using version 1.0.0 on TYPO3 8.7.

**Comment by josefglatz** [comment]
@georgringer is it expected that fetching data is possible without saving extConf once after installing ext:t3monitoring_client?

**Comment by georgringer** [comment]
By default I need that settings secure, therefore this must stay like that.
