### ISSUE TITLE
No configuration available in Extension Manager

### ISSUE THREAD

**Issue by maslme** [georgringer/t3monitoring_client#43]
After installing the latest version from github on TYPO3 9.5.6 there are no configuration options avaiblable in the Extension Manager.

t3monitoring_client 9.0.1
TYPO3 9.5.6
normal installation
PHP 7.2.13

**Comment by josefglatz** [comment]
Extension configuration was moved into _Admin Tools -> Settings -> Extension Configuration_. This is a TYPO3 core change since version >= 9.5.

Please comment if I should re-open the issue. Actually I can't reproduce your problem.
