### ISSUE TITLE
403 Error when fetching TYPO3 9 client

### ISSUE THREAD

**Issue by maslme** [georgringer/t3monitoring_client#45]
when fetching a TYPO3 9 client I got an 403 Error.

Server:
t3monitoring: latest github version
TYPO3: 8.7.26
PHP: 7.2.3

Client:
t3monitoring_client: latest github version
TYPO3: 9.5.6
PHP: 7.2.13

**Comment by opi99** [comment]
Did you configure the "allowedIps" field in extension configuration on client side?

**Comment by maslme** [comment]
The allowedIps is wildcarded - but you gave me the right hint, the secret has changed during the update process...
