### ISSUE TITLE
Exception with Maps2 extension

### ISSUE THREAD

**Issue by AureliusHogan** [georgringer/t3monitoring_client#50]
When running a scan with TYPO3 8.7.29 and extension maps2 7.1.1 activated I get the following error:

`Argument 4 passed to JWeiland\Maps2\Update\MoveOldFlexFormSettings87Update::__construct() must be an instance of TYPO3\CMS\Install\Controller\Action\Tool\UpgradeWizard or null, instance of TYPO3\CMS\Install\Report\InstallStatusReport given, called in /var/www/cup/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3969`

If I deactivate the extension the scan works perfekt.

**Comment by liayn** [comment]
Is this still an issue?

**Comment by AureliusHogan** [comment]
I tried it right now the first time since my comment again. And made a code update.

The problem is not existent anymore.
