### ISSUE TITLE
Fetching the current status not working any more for TYPO3 10.4.16

### ISSUE THREAD

**Issue by andre-spindler** [georgringer/t3monitoring_client#59]
After updating a client to current TYPO3 10 version 10.4.16, Fetching the status fails.
Client returns an exception:
![grafik](https://user-images.githubusercontent.com/5618751/118200900-836bcf80-b456-11eb-9913-76ccb43b1988.png)

Client system runs with php 7.3(.28) and is a composer installation.

**Comment by jacobsenj** [comment]
Has something to do with a new feature: https://github.com/TYPO3/TYPO3.CMS/commit/62c1956583 

I found that $GLOBALS['TYPO3_REQUEST'] is not available in the eid run. Adding

```php
                $request = ServerRequestFactory::fromGlobals();
                $GLOBALS['TYPO3_REQUEST'] = $request->withAttribute('normalizedParams', NormalizedParams::createFromRequest($request));
```

before 

```php
                $GLOBALS['TSFE'] = GeneralUtility::makeInstance(TypoScriptFrontendController::class, null, new NullSite(), $siteLanguage);
```

in `t3monitoring_client/Classes/Client.php` made it work for TYPO3 10.4.16 again. But I don't think this would be the real solution.

**Comment by tbsschmdt** [comment]
This workaround requires either fully qualified names or the following use statements:

```PHP
use TYPO3\CMS\Core\Http\ServerRequestFactory;
use TYPO3\CMS\Core\Http\NormalizedParams;
```

> ```
>                 $request = ServerRequestFactory::fromGlobals();
>                 $GLOBALS['TYPO3_REQUEST'] = $request->withAttribute('normalizedParams', NormalizedParams::createFromRequest($request));
> ```

**Comment by wowaTYPO3** [comment]
Can confirm this problem after update to 10.4.16.

**Comment by christianbltr** [comment]
Workaround works for me, I made a fork at https://github.com/christianbltr/t3monitoring_client/tree/issue-59-fetching-status-with-10-4-16
Not sure if this is the final solution, so I'm not creating a pull request.

**Comment by georgringer** [comment]
thanks! i used the same idea as I see no other way, the core changed which is fine as this is internal
