### ISSUE TITLE
Problem with TYPO3 10.4.16

### ISSUE THREAD

**Issue by alsodenn** [georgringer/t3monitoring_client#63]
The extension "t3monitoring" cannot retrieve the information from the TYPO3 installations (t3monitoring_client) with TYPO3 version 10.4.16. It worked with version 10.4.15. 

The following error appears:

`Server error: `GET domain.com/index.php?eID=t3monitoring&secret=secret` resulted in a `500 Internal Server Error` response:<!DOCTYPE html><head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> <meta name=" (truncated...)`

**Comment by joey-beech-it** [comment]
Alsodenn, which version of the client are u using. Updating to v9.2.1 solved the issue for me. 

https://github.com/georgringer/t3monitoring_client/releases/tag/9.2.1

**Comment by alsodenn** [comment]
Didn't see that there was a new version as it is not in the TER. 
Can confirm, with the new version 9.2.1 it works again. Thank you!
