### ISSUE TITLE
TypoScriptFrontendController is not initialized

### ISSUE THREAD

**Issue by mhuber84** [georgringer/t3monitoring_client#65]
With t3monitoring_client v9.2.1 in TYPO3 v11.3.3 the TypoScriptFrontendController in Classes/Client.php row 107 can not be initialized:

Here the important parts from the stacktrace:
```
...
Argument 1 passed to TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::__construct() must be an instance of TYPO3\CMS\Core\Context\Context, null given
...
.../typo3conf/ext/t3monitoring_client/Classes/Client.php(56): T3Monitor\\T3monitoringClient\\Client->collectData()
...
```

**Comment by blitz-weblab** [comment]
Hello @mhuber84 

I provide solution for TYPO3 v11 let's talk about it :) 

https://github.com/georgringer/t3monitoring_client/pull/66

**Comment by peterkraume** [comment]
@mhuber84 I've created a patch which should add support for TYPO3 9 until 11. Maybe you can give my patch a try.

**Comment by mhuber84** [comment]
Hi @peterkraume , your patch #67 works with TYPO3 11.4
