### ISSUE TITLE
PHP Warning: Undefined array key "type" in /Classes/ExtensionProvider.php line 35

### ISSUE THREAD

**Issue by maslme** [georgringer/t3monitoring_client#81]
Client Setup:
t3_monitoring_client (latest github version)
TYPO3 11.5.30
php 8.0

Server Setup:
t3_monitoring 2.0.0
TYPO3 10.4.37
php 7.4.33

When I try to fetch a clients stat I got an "PHP Warning: Undefined array key "type" in [...]/typo3conf/ext/t3monitoring_client/Classes/Provider/ExtensionProvider.php line 35" - when I change the php Version of the client to 7.4 the warning is gone.

**Comment by liayn** [comment]
This was fixed with https://github.com/georgringer/t3monitoring_client/commit/4fde85258f523b71fe81042bfed2ba008593a6cd
